name: Publish Image to GHCR

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install huggingface-cli
        uses: BSFishy/pip-action@v1
        with:
          packages: huggingface_hub[cli]

      - name: Download GGUF
        run: |
          huggingface-cli download microsoft/bitnet-b1.58-2B-4T-gguf --include "ggml-model-i2_s.gguf" --local-dir .

      - name: Checksum GGUF
        run: |
          sha256sum ggml-model-i2_s.gguf

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: bitnet-server
          labels: |
            org.opencontainers.image.description=https://huggingface.co/microsoft/bitnet-b1.58-2B-4T-gguf

      #- name: Test image
      #  run: podman run --rm -it bitnet:latest python3 run_inference_server.py -m ggml-model-i2_s.gguf -p "Why is the sky blue?"

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
